[book]
title = "从头实现µGo语言"
authors = ["chai2010"]
description = "从头开发一个迷你Go语言编译器"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/chai2010/ugo-compiler-book"
git-repository-icon = "fa-github"
