[book]
title = "µGo语言实现"
authors = ["chai2010"]
description = "如何从头开发一个迷你Go语言编译器"
language = "zh"
multilingual = false
src = "."

[build]
build-dir = "docs"

[output.html]
git-repository-url = "https://github.com/chai2010/ugo-compiler-book"
edit-url-template = "https://github.com/chai2010/ugo-compiler-book/edit/master/{path}"
git-repository-icon = "fa-github"
